name: Deploy site files

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps:
      - name: =>> Checkout Branch # 1，下载代码仓库
        uses: actions/checkout@v2
      - name: =>> Select Node Version # 选择Node版本，某些依赖安装需要固定版本
        uses: actions/setup-node@v2
        with:
          node-version: "14.18.2"

      - name: =>> Install Deps & Build # 2, 安装依赖并打包
        run: |
          yarn
          yarn build

      - name: =>> Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          timeout: "15m"
          key: ${{ secrets.KEY }}
          port: "22"
          source: ".nuxt/*,static/*,node_modules/*,nuxt.config.js,package.json,yarn.lock"
          target: /home/sites/blog
          overwrite: true